spin_manifest_version = "1"
authors = ["Navusas <D.Giedraitis7@gmail.com>"]
description = ""
name = "quick-start"
version = "1.0.0"
trigger = { type = "http", base = "/" }

[[component]]
id = "quick_start"
source = "bin/Release/net7.0/QuickStart.wasm"
[component.build]
command = "dotnet build -c Release"
[component.trigger]
route = "/..."
