spin_manifest_version = "1"
name = "my-test-microservice"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[variables]
defaulted = { default = "test value" }
required = { default = "true" }

[[component]]
id = "home"
source = "Marvellous.Site.Home/bin/Release/net7.0/Marvellous.Site.Home.wasm"
allowed_http_hosts = [ "https://spin.fermyon.dev", "http://127.0.0.1:3001" ]
files = [{ source = "Marvellous.Site.Home/assets", destination = "/assets" }]
[component.config]
defaulted = "{{ defaulted }}"
required = "{{ required }}"
[component.build]
command = "dotnet build -c Release"
workdir = "Marvellous.Site.Home"
[component.trigger]
route = "/..."